### ISSUE TITLE
Support running the TCK with Java 21

### ISSUE THREAD

**Issue by jamezp** [jakartaee/cdi-tck#484] opened 2023-10-04 22:31 UTC
Testing WildFly with version 4.0.11 with Java 21 we run into a test failure.
```
[INFO] Running org.jboss.cdi.tck.tests.definition.bean.types.ManagedBeanTypesTest
Installed WildFlyExceptionTransformer
Oct 04, 2023 3:22:44 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 2.4.0.Final
Oct 04, 2023 3:22:44 PM org.jboss.as.arquillian.container.CommonManagedDeployableContainer startInternal
INFO: Starting container with: [/usr/lib/jvm/java-21-openjdk-21.0.0.0.35-1.rolling.fc38.x86_64/bin/java, -D[Standalone], -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005, -Xms128m, -Xmx1g, -Dsignature.sigTestClasspath="${signature.sigTestClasspath}", -ea, -Djboss.home.dir=/home/jperkins/projects/wildfly/wildfly-tck-runners/wf-core-tck-runner/cdi-tck/target/wildfly, --add-exports=java.desktop/sun.awt=ALL-UNNAMED, --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED, --add-opens=java.base/java.lang=ALL-UNNAMED, --add-opens=java.base/java.lang.invoke=ALL-UNNAMED, --add-opens=java.base/java.lang.reflect=ALL-UNNAMED, --add-opens=java.base/java.io=ALL-UNNAMED, --add-opens=java.base/java.security=ALL-UNNAMED, --add-opens=java.base/java.util=ALL-UNNAMED, --add-opens=java.base/java.util.concurrent=ALL-UNNAMED, --add-opens=java.management/javax.management=ALL-UNNAMED, --add-opens=java.naming/javax.naming=ALL-UNNAMED, --add-modules=java.se, -Djava.security.manager=allow, -Djboss.home.dir=/home/jperkins/projects/wildfly/wildfly-tck-runners/wf-core-tck-runner/cdi-tck/target/wildfly, -Djboss.server.base.dir=/home/jperkins/projects/wildfly/wildfly-tck-runners/wf-core-tck-runner/cdi-tck/target/wildfly/standalone, -Djboss.server.log.dir=/home/jperkins/projects/wildfly/wildfly-tck-runners/wf-core-tck-runner/cdi-tck/target/wildfly/standalone/log, -Djboss.server.config.dir=/home/jperkins/projects/wildfly/wildfly-tck-runners/wf-core-tck-runner/cdi-tck/target/wildfly/standalone/configuration, -Dorg.jboss.boot.log.file=/home/jperkins/projects/wildfly/wildfly-tck-runners/wf-core-tck-runner/cdi-tck/target/wildfly/standalone/log/server.log, -Dlogging.configuration=file:/home/jperkins/projects/wildfly/wildfly-tck-runners/wf-core-tck-runner/cdi-tck/target/wildfly/standalone/configuration/logging.properties, -jar, /home/jperkins/projects/wildfly/wildfly-tck-runners/wf-core-tck-runner/cdi-tck/target/wildfly/jboss-modules.jar, -mp, /home/jperkins/projects/wildfly/wildfly-tck-runners/wf-core-tck-runner/cdi-tck/target/wildfly/modules, org.jboss.as.standalone, -c=standalone.xml]
Oct 04, 2023 3:22:44 PM org.jboss.remoting3.EndpointImpl <clinit>
INFO: JBoss Remoting version 5.0.24.Final
Oct 04, 2023 3:22:44 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.8.7.Final
Oct 04, 2023 3:22:44 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.8.7.Final
Oct 04, 2023 3:22:44 PM org.wildfly.security.Version <clinit>
INFO: ELY00001: WildFly Elytron version 1.19.0.Final
Oct 04, 2023 3:22:48 PM org.jboss.cdi.tck.shrinkwrap.ArchiveBuilder buildSupportLibrary
INFO: Support library built [time: 28 ms]
Oct 04, 2023 3:22:48 PM org.jboss.cdi.tck.shrinkwrap.ArchiveBuilder buildIncontainerLibrary
INFO: Incontainer library built [time: 10 ms]
Oct 04, 2023 3:22:48 PM org.jboss.cdi.tck.shrinkwrap.ArchiveBuilder build
INFO: Test archive built [info: org.jboss.cdi.tck.tests.definition.bean.types.ManagedBeanTypesTest, time: 22 ms]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 42.852 s <<< FAILURE! - in org.jboss.cdi.tck.tests.definition.bean.types.ManagedBeanTypesTest
[ERROR] org.jboss.cdi.tck.tests.definition.bean.types.ManagedBeanTypesTest.testGenericHierarchyBeanTypes  Time elapsed: 36.737 s  <<< FAILURE!
java.lang.AssertionError: Set [interface java.util.Collection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, class java.lang.Object, class org.jboss.cdi.tck.tests.definition.bean.types.Flock, interface java.util.SequencedCollection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.util.List<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, interface java.lang.Iterable<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>] (6) does not match array [class java.lang.Object, class org.jboss.cdi.tck.tests.definition.bean.types.Flock, java.util.List<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.util.Collection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.lang.Iterable<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>] (5)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.Assert.fail(Assert.java:99)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.cdi.tck.util.Assert.assertTypeSetMatches(Assert.java:88)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.cdi.tck.tests.definition.bean.types.ManagedBeanTypesTest.testGenericHierarchyBeanTypes(ManagedBeanTypesTest.java:80)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:239)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.testng.Arquillian$3.invoke(Arquillian.java:146)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:57)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.container.test.impl.execution.ContainerTestExecuter.execute(ContainerTestExecuter.java:36)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:116)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.test(EventTestRunnerAdaptor.java:139)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.testng.Arquillian.run(Arquillian.java:138)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:253)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:594)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.TestRunner.privateRun(TestRunner.java:794)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.TestRunner.run(TestRunner.java:596)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.TestNG.runSuites(TestNG.java:1063)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.testng.TestNG.run(TestNG.java:1031)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.testng.container.TestNGTestRunner.execute(TestNGTestRunner.java:51)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.protocol.servlet5.runner.ServletTestRunner.executeTest(ServletTestRunner.java:139)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.protocol.servlet5.runner.ServletTestRunner.execute(ServletTestRunner.java:117)
	at deployment.ManagedBeanTypesTesta55a8bfaa09fd13068a169c9c34d5fbdae872eb.war//org.jboss.arquillian.protocol.servlet5.runner.ServletTestRunner.doGet(ServletTestRunner.java:86)
	at jakarta.servlet.api@6.0.0//jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at jakarta.servlet.api@6.0.0//jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at org.wildfly.extension.undertow@28.0.0.Beta1//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.core@2.3.4.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:276)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:132)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@28.0.0.Beta1//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1430)
	at org.wildfly.extension.undertow@28.0.0.Beta1//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1430)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:256)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:101)
	at io.undertow.core@2.3.4.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.core@2.3.4.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1348)
	at org.jboss.xnio@3.8.8.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ManagedBeanTypesTest>Arquillian.run:138->testGenericHierarchyBeanTypes:80 Set [interface java.util.Collection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, class java.lang.Object, class org.jboss.cdi.tck.tests.definition.bean.types.Flock, interface java.util.SequencedCollection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.util.List<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, interface java.lang.Iterable<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>] (6) does not match array [class java.lang.Object, class org.jboss.cdi.tck.tests.definition.bean.types.Flock, java.util.List<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.util.Collection<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>, java.lang.Iterable<org.jboss.cdi.tck.tests.definition.bean.types.Vulture<java.lang.Integer>>] (5)
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

I've narrowed the issue down to https://github.com/jakartaee/cdi-tck/blob/931fb5369c3a5a216beb8d16a54c9d90f7c088b9/impl/src/main/java/org/jboss/cdi/tck/tests/definition/bean/types/ManagedBeanTypesTest.java#L80C30-L80C30. The issue is that in Java 21 the `java.util.List` interface extends `java.util.SequencedCollection` resulting in the found types to be of size 6 with that extra interface and the expected types with a size of 5, obviously missing the `java.util.SequencedCollection`.

I'm not too sure what could be done to fix this without upgrading to Java 21. However, this will become an issue as Jakarta EE 11 is targeting Java 21.

**Comment by manovotn** [comment] 2023-10-04 23:22
This looks like a duplicate of https://github.com/jakartaee/cdi-tck/issues/476 which was fixed by https://github.com/jakartaee/cdi-tck/pull/477 on current master (targetting next major version). Or is there something else I am missing @jamezp?

**Comment by jamezp** [comment] 2023-10-05 00:28
@manovotn Sorry, yes. I fetched the latest upstream on my local branch, but then failed to reset my local branch.

**Comment by bstansberry** [comment] 2023-10-05 15:53
@jamezp @manovotn Is the point here that WildFly wants a TCK challenge for CDI 4? AIUI the work we are doing in WildFly related to TCK and SE 21 is not about preparing for EE 11, it's about testing WildFly's EE 10 implementation.

**Comment by starksm64** [comment] 2023-10-05 15:58
Create an explicit TCK challenge if that is what you want so that it can be
accepted as a mandate of EE 10 was to be able to run on later Java SE
versions. You can then run the tck an report the failures that match the
challenge without needing a new TCK release.

**Closed** 2023-10-05 16:17 UTC

**Comment by jamezp** [comment] 2023-10-05 16:54
> Create an explicit TCK challenge if that is what you want so that it can be accepted as a mandate of EE 10 was to be able to run on later Java SE versions. You can then run the tck an report the failures that match the challenge without needing a new TCK release.
> […](#)
> On Thu, Oct 5, 2023 at 9:54 AM Brian Stansberry ***@***.***> wrote: @jamezp <https://github.com/jamezp> @manovotn <https://github.com/manovotn> Is the point here that WildFly wants a TCK challenge for CDI 4? AIUI the work we are doing in WildFly related to TCK and SE 21 is not about preparing for EE 11, it's about testing WildFly's EE 10 implementation.

Thank you. Filed https://github.com/jakartaee/cdi-tck/issues/485 as the challenge.

**Comment by manovotn** [comment] 2023-10-05 16:55
Thanks, that's definitely a valid challenge.
